-- MySQL Script generated by MySQL Workbench
-- Tue Nov  9 22:52:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UniversoLeitura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UniversoLeitura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UniversoLeitura` DEFAULT CHARACTER SET utf8 ;
USE `UniversoLeitura` ;

-- -----------------------------------------------------
-- Table `UniversoLeitura`.`ASSOCIADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`ASSOCIADOS` (
  `id_associados` INT NOT NULL AUTO_INCREMENT,
  `rg` CHAR(7) NULL,
  `nome` VARCHAR(50) NULL,
  `sobrenome` VARCHAR(50) NULL,
  `endereco` VARCHAR(150) NULL,
  `cidade` VARCHAR(50) NULL,
  `estado` VARCHAR(2) NULL,
  PRIMARY KEY (`id_associados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLeitura`.`TELEFONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`TELEFONES` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `telefone_socio` VARCHAR(100) NULL,
  `codAssoc` INT NULL,
  PRIMARY KEY (`id_telefone`),
  INDEX `fk_telefone_associado_idx` (`codAssoc` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_associado`
    FOREIGN KEY (`codAssoc`)
    REFERENCES `UniversoLeitura`.`ASSOCIADOS` (`id_associados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLeitura`.`AUTORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`AUTORES` (
  `id_autores` INT NOT NULL AUTO_INCREMENT,
  `sobrenome` VARCHAR(100) NULL,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`id_autores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLeitura`.`EDITORAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`EDITORAS` (
  `id_editoras` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(150) NULL,
  `telefone` VARCHAR(100) NULL,
  PRIMARY KEY (`id_editoras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLeitura`.`LIVROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`LIVROS` (
  `id_livro` INT NOT NULL AUTO_INCREMENT,
  `cod_ISBN` VARCHAR(13) NULL,
  `titulo` VARCHAR(200) NULL,
  `ano_criacao` DATE NULL,
  `cod_autor` INT NULL,
  `ano_publicacao` DATE NULL,
  `cod_editora` INT NULL,
  PRIMARY KEY (`id_livro`),
  INDEX `fk_livros_autores_idx` (`cod_autor` ASC) VISIBLE,
  INDEX `fk_livros_editoras_idx` (`cod_editora` ASC) VISIBLE,
  CONSTRAINT `fk_livros_autores`
    FOREIGN KEY (`cod_autor`)
    REFERENCES `UniversoLeitura`.`AUTORES` (`id_autores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livros_editoras`
    FOREIGN KEY (`cod_editora`)
    REFERENCES `UniversoLeitura`.`EDITORAS` (`id_editoras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLeitura`.`EMPRESTIMOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`EMPRESTIMOS` (
  `id_emprestimo` INT NOT NULL AUTO_INCREMENT,
  `codAssoc` INT NULL,
  `data` DATE NULL,
  `prazo_devolucao` DATE NULL,
  `data_devolucao` DATE NULL,
  PRIMARY KEY (`id_emprestimo`),
  INDEX `fk_emprestimo_associado_idx` (`codAssoc` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_associado`
    FOREIGN KEY (`codAssoc`)
    REFERENCES `UniversoLeitura`.`ASSOCIADOS` (`id_associados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLeitura`.`EXEMPLARES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`EXEMPLARES` (
  `id_exemplares` INT NOT NULL AUTO_INCREMENT,
  `cod_livro` INT NULL,
  `sinistro` TINYINT(1) NULL,
  PRIMARY KEY (`id_exemplares`),
  INDEX `fk_exemplares_idx` (`cod_livro` ASC) VISIBLE,
  CONSTRAINT `fk_exemplares`
    FOREIGN KEY (`cod_livro`)
    REFERENCES `UniversoLeitura`.`LIVROS` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLeitura`.`EMPRESTIMO_EXEMPLARES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`EMPRESTIMO_EXEMPLARES` (
  `id_emprestimo_exemplares` INT NOT NULL AUTO_INCREMENT,
  `cod_emprestimo` INT NULL,
  `cod_exemplar` INT NULL,
  PRIMARY KEY (`id_emprestimo_exemplares`),
  INDEX `fk_emprestimoExemplares_exemplares_idx` (`cod_exemplar` ASC) VISIBLE,
  INDEX `fk_emprestimoExemplares_emprestimos_idx` (`cod_emprestimo` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimoExemplares_exemplares`
    FOREIGN KEY (`cod_exemplar`)
    REFERENCES `UniversoLeitura`.`EXEMPLARES` (`id_exemplares`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimoExemplares_emprestimos`
    FOREIGN KEY (`cod_emprestimo`)
    REFERENCES `UniversoLeitura`.`EMPRESTIMOS` (`id_emprestimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
