CREATE DATABASE CARDAPIO;
USE CARDAPIO;

-- TABELA CATEGORIA(INDIVIDUAL)
CREATE TABLE CATEGORIA(
	ID_CATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    URL_IMAGEM VARCHAR(255)
);

-- TABELA CLIENTES(INDIVIDUAL)
CREATE TABLE CLIENTE(
	ID_USUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SOBRENOME VARCHAR(150),
    CPF VARCHAR(15),
    NR_CELULAR VARCHAR(20),
    EMAIL VARCHAR(100)
);

-- TABELA PRODUTOS
CREATE TABLE PRODUTO(
	ID_PRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CATEGORIA INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    IMAGEM VARCHAR(255),
    VALOR_PRODUTO DECIMAL(5,2),
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

-- TABELA CONTA
CREATE TABLE CONTA(
	ID_CONTA  INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT NOT NULL,
    DATA_HORA_CONTA DATETIME DEFAULT CURRENT_TIMESTAMP,
    VALOR_TOTAL DECIMAL(5,2),
    CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLEINTE)
);
    
-- TABELA PEDIDO
CREATE TABLE PEDIDO(
	ID_PEDIDO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
	ID_CONTA INT NOT NULL,
    QUANTIDADE INT,
    SUB_TOTAL DECIMAL(5,2),
    CONSTRAINT FK_PEDIDO_CONTA FOREIGN KEY (ID_CONTA) REFERENCES CONTA(ID_CONTA),
    CONSTRAINT FK_PEDIDO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
);


